name: lupin_music
description: "💜 Lupin Music (Flutter Edition) - Premium Luxury Dark Cyber Music Streaming App for Windows, macOS, Android & iOS"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  just_audio: ^0.9.36
  youtube_explode_dart: ^2.2.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  discord_rpc: ^1.1.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon.png
